### PR TITLE
added support for build.env

### PR DESCRIPTION
**Pull request by maxses**
The build scripts can create an file "build.env" in the build folder to feed back environment variables to laminar.
After the build, the file is parsed by laminar.

The following variables are used by laminar:

- `SOURCE_BRANCH` branch used in the SCM-checkout (e.g git) for building
- `SOURCE_VERSION` release version of the build

### CODE REVIEW

**Comment by ohwgiles** [comment]
Thanks for the PR!

In its current form I'd prefer not to merge into mainline, for a couple of reasons:
- laminar itself shouldn't know about "branches" or "source versions", these are VCS concepts that might not be relevant
- Parsing `build.env` is kind of a new interface, not sure this can be justified over using `laminarc` which is the primary interface

I could imagine for example some kind of `laminarc tag` command that would allow attaching generic key/value metadata to a run.

What exactly are you trying to achieve with this? If it's just showing extra data on the frontend for the job, what is insufficient about echoing it to the console, or redirecting it to an artifact? Is it important that they get database columns?

**Comment by maxses** [comment]
Thanks for the comments.

Sure, laminar should not handle/know about branches/versions. But not having this information available in the list of runs is a bit uncomfortable.

LAMINAR_REASON could be misused to track this information, but at least "Version" is some information that may not be available at the timepoint of triggering a build (for example 'v0.1.6-7-g5a31-ID28' containing the laminar-RUN).

`laminarc tag` is probably an better idea to achieve this and more straight forward. `build.env` was just the simplest way I came up with.

Having the information in database columns is needed to show them in the list of runs for example. Filtering may be relevant in the future.
Imagine an Sourcecode-Repository has multiple Feature-Branches, multiple (active) Release-Branches, a development branch and an main branch, all triggered via nightly builds and via commit.  It is super hard to find an specific build by having to look at each log output or artifacts.

Another possibility would be to introduce "custom fields". In that way, the words "Branch" or "Version" do not show up in laminars sourcecode but can be configured in `laminar.conf`. e.g.:
```
LAMINAR_CUSTOM_FIELD_1=sourceBranch
LAMINAR_CUSTOM_FIELD_1_LABEL=Branch
LAMINAR_CUSTOM_FIELD_1_ENV=SOURCE_BRANCH
LAMINAR_CUSTOM_FIELD_2=sourceVersion
LAMINAR_CUSTOM_FIELD_2_LABEL=Version
LAMINAR_CUSTOM_FIELD_2_ENV=SOURCE_VERSION
``` 

Regards,
   Max

**Comment by ohwgiles** [comment]
Yes, I think we can definitely provide some useful feature based along these lines with a bit of discussion, and thanks for the added context. I understand it's useful to be able to display extra data in the run list and appreciate `LAMINAR_REASON` isn't sufficient.

> Imagine an Sourcecode-Repository has multiple Feature-Branches, multiple (active) Release-Branches, a development branch and an main branch, all triggered via nightly builds and via commit.

Typically I would suggest that each different type of build would be a separate laminar job. This reduces the need for additional metadata, and it is easy for jobs to share implementations, and easy to dynamically create jobs - you can even create a job on the fly that exists only for the duration of the parent job. This is usually a good fit for things like feature branches or nightly builds, or variant builds using a different toolchain/platform target, but is less appropriate for e.g. publishing version info

> One possibility would be to introduce "custom fields" for specifying user-defined key/values. In that way, the words "Branch" or "Version" do not show up in laminars sourcecode but can be configured in laminar.conf.

I think we can do this without introducing environment variables. We could just have one new database column `metadata`, which would be populated by a json object, the key/value pairs of which would be set by `laminarc tag`, e.g. `laminarc tag version 123; laminarc tag branch foo` would result in `{ "version": "123", "branch", "foo" }`. This JSON object would be sent unmodified to the frontend, which could convert it into columns/rows in the table. It would have to union all keys in all runs in the current view to know how many columns to create, because not all runs would necessarily have all the same tags - maintaining consistency here would be up to the administrator.

How does that sound?

**Comment by maxses** [comment]
New PR is created.

**Pull request closed without merging**
